[package]
name = "assign_05_ludogame"
version = "0.1.0"
authors = ["Muhammad Jehanzaib <jehanzaib364@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"